"""initial schema

Revision ID: a1858f8339de
Revises: 
Create Date: 2025-05-14 01:20:17.526979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1858f8339de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('home_club_id', sa.Integer(), nullable=False),
    sa.Column('away_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['home_club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natural_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_foot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('current_club_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_full_name'), 'player', ['full_name'], unique=False)
    op.create_table('appearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('market_value_eur', sa.Integer(), nullable=True),
    sa.Column('highest_market_value_eur', sa.Integer(), nullable=True),
    sa.Column('OVR', sa.Integer(), nullable=True),
    sa.Column('PAC', sa.Integer(), nullable=True),
    sa.Column('SHO', sa.Integer(), nullable=True),
    sa.Column('PAS', sa.Integer(), nullable=True),
    sa.Column('DRI', sa.Integer(), nullable=True),
    sa.Column('DEF', sa.Integer(), nullable=True),
    sa.Column('PHY', sa.Integer(), nullable=True),
    sa.Column('Acceleration', sa.Integer(), nullable=True),
    sa.Column('Sprint_Speed', sa.Integer(), nullable=True),
    sa.Column('Positioning', sa.Integer(), nullable=True),
    sa.Column('Finishing', sa.Integer(), nullable=True),
    sa.Column('Shot_Power', sa.Integer(), nullable=True),
    sa.Column('Long_Shots', sa.Integer(), nullable=True),
    sa.Column('Volleys', sa.Integer(), nullable=True),
    sa.Column('Penalties', sa.Integer(), nullable=True),
    sa.Column('Vision', sa.Integer(), nullable=True),
    sa.Column('Crossing', sa.Integer(), nullable=True),
    sa.Column('Free_Kick_Accuracy', sa.Integer(), nullable=True),
    sa.Column('Short_Passing', sa.Integer(), nullable=True),
    sa.Column('Long_Passing', sa.Integer(), nullable=True),
    sa.Column('Curve', sa.Integer(), nullable=True),
    sa.Column('Dribbling', sa.Integer(), nullable=True),
    sa.Column('Agility', sa.Integer(), nullable=True),
    sa.Column('Balance', sa.Integer(), nullable=True),
    sa.Column('Reactions', sa.Integer(), nullable=True),
    sa.Column('Ball_Control', sa.Integer(), nullable=True),
    sa.Column('Composure', sa.Integer(), nullable=True),
    sa.Column('Interceptions', sa.Integer(), nullable=True),
    sa.Column('Heading_Accuracy', sa.Integer(), nullable=True),
    sa.Column('Def_Awareness', sa.Integer(), nullable=True),
    sa.Column('Standing_Tackle', sa.Integer(), nullable=True),
    sa.Column('Sliding_Tackle', sa.Integer(), nullable=True),
    sa.Column('Jumping', sa.Integer(), nullable=True),
    sa.Column('Stamina', sa.Integer(), nullable=True),
    sa.Column('Strength', sa.Integer(), nullable=True),
    sa.Column('Aggression', sa.Integer(), nullable=True),
    sa.Column('Weak_foot', sa.Integer(), nullable=True),
    sa.Column('Skill_moves', sa.Integer(), nullable=True),
    sa.Column('Preferred_foot_stat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Alternative_positions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Play_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('GK_Diving', sa.Integer(), nullable=True),
    sa.Column('GK_Handling', sa.Integer(), nullable=True),
    sa.Column('GK_Kicking', sa.Integer(), nullable=True),
    sa.Column('GK_Positioning', sa.Integer(), nullable=True),
    sa.Column('GK_Reflexes', sa.Integer(), nullable=True),
    sa.Column('League', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Weight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('playervaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market_value_eur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playervaluation')
    op.drop_table('playerstats')
    op.drop_table('gameevent')
    op.drop_table('appearance')
    op.drop_index(op.f('ix_player_full_name'), table_name='player')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('competition')
    op.drop_table('club')
    # ### end Alembic commands ###
